version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - wget https://github.com/git-lfs/git-lfs/releases/download/v3.1.4/git-lfs-linux-amd64-v3.1.4.tar.gz
      - tar xvfz git-lfs-linux-amd64-v3.1.4.tar.gz git-lfs
      - git config filter.lfs.process "${PWD}/git-lfs filter-process"
      - git config filter.lfs.smudge  "${PWD}/git-lfs smudge -- %f"
      - git config filter.lfs.clean "${PWD}/git-lfs clean -- %f"
      - ./git-lfs install
      - ./git-lfs fetch
      - ./git-lfs checkout
    pre_build:
      - pip install hatch
      - hatch run docs:linkcheck
    build:
      html:
        - hatch run docs:build --fail-on-warning
