name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check --diff'

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Hatch
        uses: pypa/hatch@install
      - run: |
          hatch run pip install -e .[dev]
      - run: |
          hatch run mypy ./src

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Hatch
        uses: pypa/hatch@install
      - run: |
          hatch run pip install -e .[dev]
      - run: |
          hatch run -- pylint --output-format github ./src

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Hatch
        uses: pypa/hatch@install
      - run: |
          hatch run pip install -e .[dev]
      - run: |
          hatch run -- flake8 ./src
