name: Release Add-on Test

on:
  push:
    branches:
      - release/*

permissions:
  contents: read

env:
  BL_VERSION: 4.5.2
  EXTENSION_NAME: paws_bakery

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    permissions:
      contents: write
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      - name: Force release branch to be at workflow sha
        run: git reset --hard ${{ github.sha }}

      - name: Verify upstream has NOT changed
        run: bash .github/workflows/verify_upstream_not_changed.sh

      - name: Create release branch
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: 'github-actions'
          git_committer_email: 'actions@users.noreply.github.com'
          # vcs_release: false
          tag: false

      - name: Ensure the release metadata is set
        run: |
          test -n "${{ steps.release.outputs.released }}"
          test -n "${{ steps.release.outputs.tag }}"
          test -n "${{ steps.release.outputs.version }}"

      # - name: Create release
      #   id: release2
      #   uses: python-semantic-release/python-semantic-release@v10.3.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     git_committer_name: 'github-actions'
      #     git_committer_email: 'actions@users.noreply.github.com'
      #     # vcs_release: false
      # - name: Ensure the release metadata is set
      #   run: |
      #     test -n "${{ steps.release2.outputs.released }}"
      #     test -n "${{ steps.release2.outputs.tag }}"
      #     test -n "${{ steps.release2.outputs.version }}"

#   publish:
#     runs-on: ubuntu-latest
#     needs: release
#     if: ${{ needs.release.outputs.released == 'true' || inputs.force_upload }}
#     steps:
#       - name: Ensure the release metadata is set
#         run: |
#           test -n "${{ needs.release.outputs.released }}"
#           test -n "${{ needs.release.outputs.tag }}"
#           test -n "${{ needs.release.outputs.version }}"
#
#       - uses: actions/checkout@v5
#         with:
#           # FIXME: doesn't work because tag may be older than workflow actions
#           ref: ${{ needs.release.outputs.tag }}
#           lfs: true
#
#       - name: Build Extension
#         id: build
#         uses: ./.github/actions/blender-extension-build
#         with:
#           blender_version: ${{ env.BL_VERSION }}
#           extension_name: ${{ env.EXTENSION_NAME }}
#
#       - name: Upload to GitHub Release Assets
#         uses: python-semantic-release/publish-action@v10.3.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ needs.release.outputs.tag }}
#           verbosity: 2
#
#   deploy:
#     runs-on: ubuntu-latest
#     needs: release
#     if: ${{ needs.release.outputs.released == 'true' }}
#
#     permissions:
#       contents: read
#       id-token: write
#
#     steps:
#       - name: Setup | Download Build Artifacts
#         uses: actions/download-artifact@v4
#         id: artifact-download
#         with:
#           name: distribution-artifacts
#           path: dist
#
#       # ------------------------------------------------------------------- #
#       # Python Semantic Release is not responsible for publishing your      #
#       # python artifacts to PyPI. Use the official PyPA publish action      #
#       # instead. The following steps are an example but is not guaranteed   #
#       # to work as the action is not maintained by the                      #
#       # python-semantic-release team.                                       #
#       # ------------------------------------------------------------------- #
#
#       # see https://docs.pypi.org/trusted-publishers/
#       - name: Publish package distributions to PyPI
#         uses: pypa/gh-action-pypi-publish@@SHA1_HASH # vX.X.X
#         with:
#           packages-dir: dist
#           print-hash: true
#           verbose: true
